### ISSUE TITLE
No PostCSS Config found

### ISSUE THREAD

**Issue by shettyshubha21** [shrivatsaBhatP/my-react-template#1]
![Screenshot from 2021-04-07 16-38-51](https://user-images.githubusercontent.com/70942914/113858790-c389c380-97c1-11eb-8269-ae4be601179e.png)

**Comment by shrivatsabhatp** [comment]
https://webpack.js.org/loaders/postcss-loader/ 
install post-css loader and update the webpack config

`  {
            loader: `postcss-loader`,
            options: {
              options: {},
            }
          },`
